version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: jotanunes-postgres
    environment:
      POSTGRES_DB: system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - jotanunes-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: jotanunes-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - jotanunes-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jotanunes-app
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=my-secret-key
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    ports:
      - "8080:8080"
    networks:
      - jotanunes-network

networks:
  jotanunes-network:
    driver: bridge

volumes:
  postgres-data:
