services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jotanunes-app
    restart: unless-stopped
    environment:
      - JWT_SECRET=my-secret-key
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - SUPABASE_PASSWORD=${SUPABASE_PASSWORD}
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 3
    networks:
      - jotanunes-network

networks:
  jotanunes-network:
    driver: bridge
